- name: Comprobar uso de disco y detectar mayor ocupación
  hosts: all
  gather_facts: no

  vars:
    unidad_objetivo: "C:\\"
    top_carpetas: 10

  tasks:
    - name: Obtener espacio de discos
      ansible.windows.win_shell: |
        Get-PSDrive -PSProvider FileSystem |
        Select Name,
               @{N='UsedGB';E={[math]::Round($_.Used/1GB,2)}},
               @{N='FreeGB';E={[math]::Round($_.Free/1GB,2)}}

      register: disk_info

    - name: Mostrar espacio de discos
      ansible.builtin.debug:
        var: disk_info.stdout_lines

    - name: Obtener TOP carpetas con mayor ocupación en C
      ansible.windows.win_shell: |
        Get-ChildItem {{ unidad_objetivo }} -Directory -ErrorAction SilentlyContinue |
        ForEach-Object {
          $size = (Get-ChildItem $_.FullName -Recurse -ErrorAction SilentlyContinue |
                   Measure-Object Length -Sum).Sum
          [PSCustomObject]@{
            Folder = $_.FullName
            SizeGB = [math]::Round($size/1GB,2)
          }
        } |
        Sort-Object SizeGB -Descending |
        Select-Object -First {{ top_carpetas }}

      register: top_folders

    - name: Mostrar carpetas más pesadas
      ansible.builtin.debug:
        var: top_folders.stdout_lines
