---
- name: Levantar servicios Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Asegurar servicios en ejecución
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
      loop: "{{ services_ordered }}"
