---
- name: Levantar servicios Windows y guardar los que se levantaron
  hosts: all
  gather_facts: no

  tasks:
    - name: Asegurar servicios en ejecución
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
      loop: "{{ services_ordered }}"
      register: servicios_resultado
      ignore_errors: true

    - name: Detectar servicios levantados por Ansible
      set_fact:
        servicios_levantados: >-
          {{ servicios_resultado.results
             | selectattr('changed','equalto',true)
             | map(attribute='item')
             | list }}

- name: Enviar Telegram desde el controller SOLO si hubo cambios
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Enviar Telegram (un mensaje por host que tuvo cambios)
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_id }}"
          text: |
            ⚠️ Ansible levantó servicios en {{ item }}:
            {{ hostvars[item].servicios_levantados | join(', ') }}
        status_code: 200
      loop: "{{ groups['all'] }}"
      when:
        - hostvars[item].servicios_levantados is defined
        - hostvars[item].servicios_levantados | length > 0
