- name: Comprobar y asegurar servicio Windows en ejecuci칩n
  hosts: all
  gather_facts: no

  tasks:
    - name: Consultar estado actual del servicio
      win_service:
        name: "{{ service_name }}"
      register: initial_state

    - name: Arrancar el servicio si no est치 en running
      win_service:
        name: "{{ service_name }}"
        state: started
      when: initial_state.state != 'running'

    - name: Reconsultar estado final del servicio
      win_service:
        name: "{{ service_name }}"
      register: final_state

    - name: Validar estado final
      fail:
        msg: "ERROR: El servicio {{ service_name }} NO est치 levantado (estado: {{ final_state.state }})"
      when: final_state.state != 'running'

    - name: Confirmar servicio levantado
      debug:
        msg: "OK: El servicio {{ service_name }} est치 LEVANTADO"
