- name: Asegurar servicios Windows siempre levantados
  hosts: all
  gather_facts: no

  tasks:
    - name: Asegurar servicios en ejecución (ordenado)
      ansible.windows.win_service:
        name: "{{ item }}"
        state: started
      loop: "{{ services_ordered }}"
